"""create_activities

Revision ID: dab366ee848f
Revises:
Create Date: 2025-08-11 15:24:50.848028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dab366ee848f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "level <=3", name=op.f("ck_activities_level_check")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["activities.id"],
            name=op.f("fk_activities_parent_id_activities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activities")),
    )
    op.create_index(
        op.f("ix_activities_name"), "activities", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_activities_name"), table_name="activities")
    op.drop_table("activities")
    # ### end Alembic commands ###
