"""create_buildings

Revision ID: 53c21b5a762d
Revises: dab366ee848f
Create Date: 2025-08-11 15:27:43.512178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "53c21b5a762d"
down_revision: Union[str, None] = "dab366ee848f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buildings")),
    )
    op.create_index(
        op.f("ix_buildings_latitude"), "buildings", ["latitude"], unique=False
    )
    op.create_index(
        op.f("ix_buildings_longitude"),
        "buildings",
        ["longitude"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_buildings_longitude"), table_name="buildings")
    op.drop_index(op.f("ix_buildings_latitude"), table_name="buildings")
    op.drop_table("buildings")
    # ### end Alembic commands ###
